// Generated by tools/generate_lcd_font.py; do not edit by hand.
#ifndef LCD_FONT_12X24_H
#define LCD_FONT_12X24_H
#include <stdint.h>

#define LCD_FONT_12X24_WIDTH 12u
#define LCD_FONT_12X24_HEIGHT 24u
#define LCD_FONT_12X24_GLYPH_COUNT 196u

extern const uint16_t
    lcd_font_12x24_bitmap[LCD_FONT_12X24_GLYPH_COUNT][LCD_FONT_12X24_HEIGHT];

#endif
