-d C:\Users\Giuliano\Documents\Embarcadero\Studio\Projects\TangNano\9K\LCD\impl\gwsynthesis\LCD.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Giuliano\Documents\Embarcadero\Studio\Projects\TangNano\9K\LCD\src\LCD.cst
-cfg C:\Users\Giuliano\Documents\Embarcadero\Studio\Projects\TangNano\9K\LCD\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
