#!/usr/bin/env python3
"""Generate the STM32 12x24 bitmap font table from a Terminus BDF file."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


WIDTH = 12
HEIGHT = 24
CODEPOINTS = tuple(range(0x20, 0x7F)) + tuple(range(0xA0, 0x100)) + (
    0x20AC,
    0x2190,
    0x2191,
    0x2192,
    0x2193,
)


def read_bdf(path: Path) -> dict[int, tuple[int, ...]]:
    lines = path.read_text(encoding="ascii").splitlines()
    glyphs: dict[int, tuple[int, ...]] = {}
    encoding: int | None = None
    bitmap: list[int] | None = None

    for line in lines:
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("BBX ") and encoding in CODEPOINTS:
            width, height, x_offset, y_offset = map(int, line.split()[1:])
            if (width, height, x_offset, y_offset) != (WIDTH, HEIGHT, 0, -5):
                raise ValueError(
                    f"U+{encoding:04X}: unexpected BBX "
                    f"{width} {height} {x_offset} {y_offset}"
                )
        elif line == "BITMAP" and encoding in CODEPOINTS:
            bitmap = []
        elif line == "ENDCHAR":
            if encoding in CODEPOINTS:
                if bitmap is None or len(bitmap) != HEIGHT:
                    raise ValueError(f"U+{encoding:04X}: expected {HEIGHT} rows")
                glyphs[encoding] = tuple(bitmap)
            encoding = None
            bitmap = None
        elif bitmap is not None:
            # BDF pads each 12-bit row on the right to a 16-bit boundary.
            bitmap.append(int(line, 16) >> (16 - WIDTH))

    missing = [codepoint for codepoint in CODEPOINTS if codepoint not in glyphs]
    if missing:
        raise ValueError("missing glyphs: " + ", ".join(f"U+{cp:04X}" for cp in missing))
    return glyphs


def generate_header() -> str:
    return """// Generated by tools/generate_lcd_font.py; do not edit by hand.
#ifndef LCD_FONT_12X24_H
#define LCD_FONT_12X24_H
#include <stdint.h>

#define LCD_FONT_12X24_WIDTH 12u
#define LCD_FONT_12X24_HEIGHT 24u
#define LCD_FONT_12X24_GLYPH_COUNT 196u

extern const uint16_t
    lcd_font_12x24_bitmap[LCD_FONT_12X24_GLYPH_COUNT][LCD_FONT_12X24_HEIGHT];

#endif
"""


def generate_source(source: Path, glyphs: dict[int, tuple[int, ...]]) -> str:
    digest = hashlib.sha256(source.read_bytes()).hexdigest().upper()
    output = [
        "// Generated by tools/generate_lcd_font.py; do not edit by hand.",
        "// Derived from ter-u24n.bdf by Dimitar Toshkov Zhekov.",
        "// Font data: SIL Open Font License 1.1; see third_party/terminus-font-4.49.1-master/OFL.TXT.",
        f"// Source SHA-256: {digest}",
        '#include "lcd_font_12x24.h"',
        "",
        "const uint16_t",
        "lcd_font_12x24_bitmap[LCD_FONT_12X24_GLYPH_COUNT][LCD_FONT_12X24_HEIGHT] = {",
    ]
    for codepoint in CODEPOINTS:
        rows = glyphs[codepoint]
        output.append(f"    // U+{codepoint:04X}")
        output.append("    {" + ", ".join(f"0x{row:03X}" for row in rows) + "},")
    output.extend(("};", ""))
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("bdf", type=Path)
    parser.add_argument("header", type=Path)
    parser.add_argument("source", type=Path)
    args = parser.parse_args()

    glyphs = read_bdf(args.bdf)
    args.header.write_text(generate_header(), encoding="ascii", newline="\n")
    args.source.write_text(generate_source(args.bdf, glyphs), encoding="ascii", newline="\n")
    print(f"generated {len(CODEPOINTS)} glyphs, {len(CODEPOINTS) * HEIGHT * 2} bitmap bytes")


if __name__ == "__main__":
    main()
